apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque
stringData:
  mysql-root-password: rootpassword123
  mysql-database: wordpress
  mysql-user: wpuser
  mysql-password: wppassword123