apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"longhorn-ui","app.kubernetes.io/instance":"longhorn","app.kubernetes.io/name":"longhorn","app.kubernetes.io/version":"v1.7.0"},"name":"longhorn-frontend","namespace":"longhorn-system"},"spec":{"ports":[{"name":"http","nodePort":null,"port":80,"targetPort":"http"}],"selector":{"app":"longhorn-ui"},"type":"ClusterIP"}}
    tailscale.com/hostname: longhorn
    tailscale.com/proxy-group: ingress-proxies
  creationTimestamp: "2026-03-25T23:34:03Z"
  finalizers:
  - tailscale.com/service-pg-finalizer
  labels:
    app: longhorn-ui
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.7.0
  name: longhorn-frontend
  namespace: longhorn-system
  resourceVersion: "479925"
  uid: 164646cf-5277-43ce-aebe-40c304c73496
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.233.37.145
  clusterIPs:
  - 10.233.37.145
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: tailscale
  ports:
  - name: http
    nodePort: 31714
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: longhorn-ui
  sessionAffinity: None
  type: LoadBalancer
status:
  conditions:
  - lastTransitionTime: "2026-03-28T19:49:09Z"
    message: 3/3 proxy backends ready and advertising
    reason: IngressSvcConfigured
    status: "True"
    type: TailscaleIngressSvcConfigured
  loadBalancer:
    ingress:
    - hostname: longhorn.mastodon-dominant.ts.net
      ip: 100.88.6.47
      ipMode: VIP
