apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"tailscale.com/expose":"true"},"name":"wordpress","namespace":"wordpress"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"wordpress"},"type":"LoadBalancer"}}
    tailscale.com/expose: "true"
  creationTimestamp: "2026-03-27T15:56:43Z"
  finalizers:
  - tailscale.com/finalizer
  name: wordpress
  namespace: wordpress
  resourceVersion: "226889"
  uid: 7bedf1d8-6a63-413a-933c-f57578e90f9c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.233.9.163
  clusterIPs:
  - 10.233.9.163
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31113
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  sessionAffinity: None
  type: LoadBalancer
status:
  conditions:
  - lastTransitionTime: "2026-03-28T09:51:34Z"
    message: ProxyCreated
    reason: ProxyCreated
    status: "True"
    type: TailscaleProxyReady
  loadBalancer: {}
