apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-test
  template:
    metadata:
      labels:
        app: longhorn-test
    spec:
      containers:
      - name: test-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["while true; do date >> /data/test.txt; sleep 10; done"]
        volumeMounts:
        - name: test-volume
          mountPath: /data
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: longhorn-test-pvc
