apiVersion: v1
kind: Pod
metadata:
  name: longhorn-persistence-writer
  namespace: testing
spec:
  restartPolicy: Never
  containers:
    - name: writer
      image: nginx:stable-alpine
      command:
        - /bin/sh
        - -c
        - sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: longhorn-persistence-test
